[package]
name = "pocketcasts"
version = "0.1.0"
authors = ["Max <maxjoehnk@gmail.com>"]

[dependencies]
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9"
cookie = "0.10"